# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Ihor Shevchuk

[tools]
tuist = "4.158.1"
swiftlint = "latest"

[tasks.install]
description = "Resolve and fetch SPM dependencies (Package.swift)"
run = "tuist install"

[tasks.generate]
description = "Generate the workspace"
run = """
   tuist version
   tuist install
   tuist generate --no-open --verbose
"""
