// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Ihor Shevchuk

import Foundation
import PiperAppUtils

enum DownloadEvent {
    case progress(Double)
    case finished(FileManager.ModelPaths)
}

protocol VoiceLoadListener: AnyObject {
    func progressUpdated(_ progress: Float)
}

class VoiceLoader: NSObject {
    private enum Error: Swift.Error {
        case nilURL
        case loadingFailed
        case wrongModelInfo
        case checksumMismatch
    }
    private enum Constants {
        // Default base repo for voices (used to construct resolve URLs when manifest provides relative paths)
        static let baseURL = "https://huggingface.co/IhorShevchuk/piper1-voices-fp16-quantized/resolve/main"
        static let sampesBaseURL = "https://rhasspy.github.io/piper-samples/samples"

        // Allow overriding the voices index via environment or app bundle in the future.
        static var voicesURL: URL? {
            return URL(string: "\(Constants.baseURL)/voices.json")
        }
    }
    
    private var continuations: [Int: CheckedContinuation<URL, Swift.Error>] = [:]
    private var observations: [Int: NSKeyValueObservation] = [:]
    
    private lazy var operationQueue: OperationQueue = {
        OperationQueue()
    }()
    
    private lazy var urlSession: URLSession = {
        URLSession(configuration: .default,
                   delegate: self,
                   delegateQueue: operationQueue)
    }()
    
    private func load<Item: Decodable>(url: URL?) async throws -> Item {
        guard let url else {
            throw Error.nilURL
        }
        
        let (data, _) = try await URLSession.shared.data(from: url)
        let decoder = JSONDecoder()
        return try decoder.decode(Item.self, from: data)
    }
    
    func loadVoices() async throws -> [Voice] {
        // Prefer a bundled English-only manifest when available (generated by scripts/generate_english_manifest.py)
        // Check multiple candidate resource names/paths so the manifest can be included via different build setups.
        let bundleCandidates: [URL?] = [
            Bundle.main.url(forResource: "huggingface_piper_en", withExtension: "json"),
            Bundle.main.url(forResource: "voices_english_manifest", withExtension: "json"),
            Bundle.main.url(forResource: "huggingface_piper_en", withExtension: "json", subdirectory: "manifests"),
            Bundle.main.resourceURL?.appendingPathComponent("manifests/huggingface_piper_en.json")
        ]

        for candidate in bundleCandidates {
            if let local = candidate {
                do {
                    let data = try Data(contentsOf: local)
                    let decoder = JSONDecoder()
                    let allVoices = try decoder.decode([String: Voice].self, from: data)
                    return Array(allVoices.values)
                } catch {
                    Log.debug("Failed to load local voices manifest at \(local): \(error). Trying next candidate.")
                }
            }
        }

        // Load the upstream voices.json index and filter to English-only entries to reduce UI clutter
        let allVoices: [String: Voice] = try await load(url: Constants.voicesURL)
        let englishOnly = allVoices.values.filter { voice in
            voice.language.family.lowercased() == "en" || voice.language.code.lowercased().hasPrefix("en")
        }
        return Array(englishOnly)
    }

    func sampleURL(for voice: Voice, speaker: String = "0") -> URL? {
        let languageCode = voice.language.code
        let languageFamily = languageCode.split(separator: "_").first.map(String.init) ?? languageCode
        let path = "\(languageFamily)/\(languageCode)/\(voice.name)/\(voice.quality)/speaker_\(speaker).mp3"
        return URL(string: "\(Constants.sampesBaseURL)/\(path)")
    }
    
    func download(voice: Voice) -> AsyncThrowingStream<DownloadEvent, Swift.Error> {
        AsyncThrowingStream { continuation in
            Task {
                do {
                    guard let modelPath = voice.modelPath,
                          let jsonPath = voice.jsonPath else {
                        throw Error.loadingFailed
                    }

                    // Support absolute URLs in the manifest; if paths are relative, resolve against baseURL
                    func resolve(_ path: String) -> URL? {
                        if let u = URL(string: path), u.scheme != nil {
                            return u
                        }
                        return URL(string: "\(Constants.baseURL)/\(path)")
                    }

                    // Prefer explicit file URLs from the manifest when available
                    let resolvedJSONURL: URL?
                    if let jf = voice.jsonFileURL {
                        resolvedJSONURL = jf
                    } else {
                        resolvedJSONURL = resolve(jsonPath)
                    }

                    let resolvedModelURL: URL?
                    if let mf = voice.modelFileURL {
                        resolvedModelURL = mf
                    } else {
                        resolvedModelURL = resolve(modelPath)
                    }

                    guard let jsonURL = resolvedJSONURL, let modelURL = resolvedModelURL else {
                        throw Error.nilURL
                    }

                    // JSON is tiny → weight 5%
                    let jsonExpectedMD5 = voice.files[jsonPath]?.md5_digest
                    let jsonLocalURL = try await self.downloadFile(
                        from: jsonURL,
                        weight: 0.05,
                        baseProgress: 0.0,
                        expectedMD5: jsonExpectedMD5,
                        continuation: continuation
                    )
                    
                    if (try? ModelInfo.create(from: jsonLocalURL)) == nil {
                        try? FileManager.default.removeItem(at: jsonLocalURL)
                        throw Error.wrongModelInfo
                    }

                    // Model is large → weight 95%
                    let modelExpectedMD5 = voice.files[modelPath]?.md5_digest
                    let modelLocalURL = try await self.downloadFile(
                        from: modelURL,
                        weight: 0.95,
                        baseProgress: 0.05,
                        expectedMD5: modelExpectedMD5,
                        continuation: continuation
                    )

                    guard let paths = FileManager.ModelPaths(model: modelLocalURL,
                                                             json: jsonLocalURL) else {
                        throw Error.loadingFailed
                    }

                    continuation.yield(.finished(paths))
                    continuation.finish()

                } catch {
                    continuation.finish(throwing: error)
                }
            }
        }
    }
    
    private func downloadFile(
        from url: URL,
        weight: Double,
        baseProgress: Double,
        expectedMD5: String? = nil,
        continuation: AsyncThrowingStream<DownloadEvent, Swift.Error>.Continuation
    ) async throws -> URL {

        let task = urlSession.downloadTask(with: url)
        let id = task.taskIdentifier

        let observation = task.progress.observe(\.fractionCompleted) { progress, _ in
            let total = baseProgress + progress.fractionCompleted * weight
            continuation.yield(.progress(total))
        }

        observations[id] = observation

        let localURL = try await withCheckedThrowingContinuation { cont in
            continuations[id] = cont
            task.resume()
        }

        // If an expected MD5 is provided in the manifest, validate the downloaded file
        if let expected = expectedMD5 {
            do {
                let md5 = try localURL.md5String()
                if md5.lowercased() != expected.lowercased() {
                    try? FileManager.default.removeItem(at: localURL)
                    throw Error.checksumMismatch
                }
            } catch {
                try? FileManager.default.removeItem(at: localURL)
                throw error
            }
        }

        return localURL
    }
}

extension VoiceLoader: URLSessionDownloadDelegate {
    
    func urlSession(_ session: URLSession, downloadTask: URLSessionDownloadTask, didFinishDownloadingTo location: URL) {
        let id = downloadTask.taskIdentifier
        
        do {
            let tempLocation = try FileManager.default.moveToTemporaryDirectory(fileURL: location)
            continuations[id]?.resume(returning: tempLocation)
        } catch {
            Log.error("Failed to move file to temporary location: \(error)")
            continuations[id]?.resume(throwing: error)
        }
        
        continuations[id] = nil
        observations[id]?.invalidate()
        observations[id] = nil
    }

    private func urlSession(
        _ session: URLSession,
        task: URLSessionTask,
        didCompleteWithError error: Error?
    ) {
        let id = task.taskIdentifier
        continuations[id]?.resume(throwing: error ?? URLError(.unknown))
        continuations[id] = nil
        observations[id]?.invalidate()
        observations[id] = nil
    }
}
